name: Build (Windows)

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller pyinstaller-hooks-contrib

      - name: Install UPX (for maximum compression)
        run: choco install upx -y

      - name: Build with PyInstaller (onefile, UPX compressed, lite)
        shell: pwsh
        run: |
          pyinstaller `
            --noconfirm `
            --clean `
            --onefile `
            --name WarpAccountManager `
            --paths src `
            --exclude-module playwright `
            --exclude-module playwright_stealth `
            --exclude-module curl_cffi `
            --exclude-module tests `
            --add-data "src/proxy/warp_proxy_script.py;src/proxy" `
            main.py

      - name: Prepare artifact
        shell: pwsh
        run: |
          $exe = "dist/WarpAccountManager.exe"
          if (!(Test-Path $exe)) { throw "Executable not found: $exe" }
          Compress-Archive -Path $exe -DestinationPath "WarpAccountManager-win64-min.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WarpAccountManager-win64-min-${{ github.run_number }}
          path: WarpAccountManager-win64-min.zip

